version: '3.9'
services:
  pleo-antaeus:
    container_name: pleo-antaeus
    build: .
    ports:
      - "8000:8000"
    expose:
      - 8000

  scheduler:
    build: scheduler-app/
    container_name: scheduler
    depends_on:
      - pleo-antaeus
